[package]
name = "mmxxiv_day01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
counter = "0.6.0"
indoc = "2.0.4"
