[package]
name = "mmxxiii_day7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.95"
counter = "0.6.0"
indoc = "2.0.5"
once_cell = "1.20.2"
regex = "1.11.1"
test-case = "3.3.1"
