[package]
name = "mmxv_day21"
version = "0.1.0"
edition = "2021"

[lints.clippy]
pedantic = "deny"

[dependencies]
ahash = "0.8.11"
anyhow = "1.0.94"
indoc = "2.0.5"
once_cell = "1.20.2"
regex = "1.11.1"
