[package]
name = "mmxxiv_day17"
version = "0.1.0"
edition = "2021"

[lints.clippy]
pedantic = "deny"

[dependencies]
anyhow = "1.0.95"
indoc = "2.0.5"
itertools = "0.14.0"
rayon = "1.10.0"
test-case = "3.3.1"
thiserror = "2.0.9"
