[package]
name = "mmxxii_day10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
indoc = "2.0"
once_cell = "1.16.0"
regex = "1.7.0"
