[package]
name = "mmxxi_day13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.5"
anyhow = "1.0"
ahash = "0.8.11"

[dev-dependencies]
test-case = "3.3"
