[package]
name = "mmxxiii_day01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
indoc = "2.0.4"
once_cell = "1.18.0"
regex = "1.10.2"
