[package]
name = "mmxxii_day20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
indoc = "2.0"
test-case = "3.3"
