[package]
name = "mmxxii_day13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.2"
anyhow = "1.0.66"
indoc = "1.0.7"
test-case = "2.2.2"
