[package]
name = "astar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.11"
num = "0.4.3"
priority-queue = "2.1.1"

[dev-dependencies]
anyhow = "1.0.95"
